"""
Educator Copilot — Slide Exporter
===================================
Exports generated remedial slides to PPTX format using python-pptx.
"""

import io
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
except ImportError:
    Presentation = None


def export_to_pptx(slides_data: list) -> bytes:
    """
    Generate a PPTX file from the remedial slides data.
    Returns the file content as bytes.
    """
    if Presentation is None:
        raise RuntimeError("python-pptx belum terinstal. Jalankan: pip install python-pptx")

    prs = Presentation()

    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Remedial & Review Materi"
    subtitle.text = "Generated by Educator Copilot AI"

    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1]
    
    for s_data in slides_data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = s_data.get("title", "Untitled Slide")
        
        tf = body_shape.text_frame
        tf.text = s_data.get("content", "")
        
        for point in s_data.get("key_points", []):
            p = tf.add_paragraph()
            p.text = point
            p.level = 1

    # Save to BytesIO
    ppt_stream = io.BytesIO()
    prs.save(ppt_stream)
    ppt_stream.seek(0)
    return ppt_stream.read()
